version: '{build}'
image: Visual Studio 2022
environment:
  SonarCloudToken:
    secure: Mznw9m1tlkSK+e7Q+GHu2yW8eiKeAWi/11Dh723cbL09JzsXY9yQRBfrTB5J7Yj4
install:
- ps: >-
    dotnet tool install --global coverlet.console

    dotnet tool install --global dotnet-sonarscanner
build_script:
- set JAVA_HOME=C:\Program Files\Java\jdk17
- set PATH=%JAVA_HOME%\bin;%PATH%
- ps: >-
    dotnet sonarscanner begin /d:sonar.login="$env:SonarCloudToken" /k:"jorgeyanesdiez_CIStatusAggregator" /d:sonar.cs.opencover.reportsPaths="coverage.xml"

    dotnet build --no-incremental
test_script:
- ps: >-
    coverlet .\CIStatusAggregatorTest\bin\Debug\net6.0\CIStatusAggregatorTest.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"

    dotnet sonarscanner end /d:sonar.login="$env:SonarCloudToken"